### PR TITLE
Remove need for weight tying in MosaicGPT

### PR DESCRIPTION
**Pull request by vchiley**
Torch has a bug when using `'meta'` tensors with FSDP and trying to do weight tying. TLDR its broken.
Composer workaround wont land in 0.13 release; this workaround removes the need for weight tying until the fix is merged into the following release.

### CODE REVIEW

**Comment by abhi-mosaic** [comment]
Do we need any updates to the the PyTest that confirms MosaicGPT is equivalent to HF GPT2?

**Comment by vchiley** [comment]
@abhi-mosaic done
Note: test was accidentally renamed incorrectly ([llm/tests/compare_hf_v_mosaic_gpt.py → llm/tests/test_hv_f_mosaic_gpt.py](https://github.com/mosaicml/examples/commit/77aed731006c86d7f506a183d9e0f5b86e5f6af0#diff-43841f663a8053417563de90b297db70c251c837976dd10e4ebdf8ee04d02b22)); fixing this as well `llm/tests/test_hv_f_mosaic_gpt.py → llm/tests/test_hf_v_mosaic_gpt.py` .

**Review by abhi-mosaic — APPROVED** [review]
LGTM! Are tests part of CI now or is that still TODO btw?

**Comment by abhi-mosaic** [comment]
never mind I answered my own question :) no CI yet

**Pull request merged**
