### PR TITLE
hf bert yaml fix

### PR DESCRIPTION
**Pull request by jacobfulano**
There is a small typo in the HF bert yaml that needs to be fixed, namely `attention_probs_dropout_prob: 0.1 # bert-base default`. The repo currently sets dropout to 0.0, which is not the default.

This is my mistake from last week.

### CODE REVIEW

**Review by alextrott16 — APPROVED** [review]
LGTM

**Comment by alextrott16** [comment]
@jacobfulano Was there an issue with `low_precision_layernorm`? Just curious what motivated the reversion.

**Comment by jacobfulano** [comment]
Additionally, according to Nikhil `low_precision_layernorm` has issues - namely Low Precision LayerNorm is not scriptable (i.e. we cannot use torchscript to export a model with LowPrecision LayerNorm for inference), making it inferior to Fused LayerNorm for users who want to export their models (see his [PR comment here](https://github.com/mosaicml/composer/pull/1931#issue-1564992812)).

I've therefore changed the BERT yamls back to `fused_layernorm`

**Review by samhavens — APPROVED** [review]
LGTM

**Comment by abhi-mosaic** [comment]
should we be merging this to release branch @dakinggg

**Pull request merged**
