### PR TITLE
Allow dictconf to be null

### PR DESCRIPTION
**Pull request by dskhudia**
config for loggers, callbacks and algorithms can now be overridden via commandline. 

Example: 
`composer main.py yamls/mosaic_gpt/125m.yaml algorithms=null`

### CODE REVIEW

**Comment by dblalock** [comment]
when you say "can be overridden," do you mean "can be set to None" specifically? And did this not work before? I didn't try it but I would expect `[whatever(k, v) for k, v in cfg.get(maybe_dict, {}]` to result in `[]` if maybe_dict is `None`. Could just be me not understanding some details about omegaconf though.

**Comment by dskhudia** [comment]
It didn't work before. with `composer main.py yamls/mosaic_gpt/125m.yaml algorithms=null` `cfg.get('algorithms', {})` results in `None` and that has no `items` method.

**Review by dblalock — APPROVED** [review]
Questions resolved via slack discussion.

My main concern is that readers (such as apparently me after a long day...) might not think about the edge case (i.e., `cfg.get('key', {})` returning None if `key`'s value is None, rather than missing) and be tempted to shorten this code, silently breaking stuff. 

To help mitigate this risk (and save space in general), I suggested a more compact version + added a quick mention of why it's written this way.

**Comment by dskhudia** [comment]
@dblalock Thanks for the suggestions. Accepted and will merge if the tests pass.

**Comment by abhi-mosaic** [comment]
@dskhudia heads up, I think we need to rebase this change on `main` now that #90 has been merged.

**Comment by dblalock** [comment]
So I think we accidentally merged `(cfg.get('algorithms' or {})` instead of `(cfg.get('algorithms') or {})`. Which probably won't work?

**Comment by dskhudia** [comment]
uh-oh! Let me make fix PR. I am surprised CI tests didn't detect it.

**Comment by dskhudia** [comment]
@dblalock added https://github.com/mosaicml/examples/pull/101

**Pull request merged**
